apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: warunaman/multi-client
          ports:
            - containerPort: 3000
          resources:             # <-- ADDED: Resource Definition
            requests:
              cpu: "100m"        # Requesting 100 millicores (0.1 CPU core)
              memory: "256Mi"    # Requesting 256 Megabytes
            limits:
              cpu: "300m"        # Allowing up to 300 millicores
              memory: "512Mi"    # Allowing up to 512 Megabytes